category_names_type = ["Air Terminals", "Analytical Links","Analytical Pipe Connections","Assemblies", "Audio Visual Devices","Cable Tray Fittings", "Cable Tray Runs", "Cable Trays", "Casework", "Ceilings", "Columns", "Communication Devices", "Conduit Fittings", "Conduit Runs", "Conduits", "Curtain Panels", "Curtain Systems", "Curtain Wall Mullions", "Data Devices", "Detail Items", "Doors", "Duct Accessories", "Duct Fittings", "Duct Insulations",
 "Duct Linings", "Duct Placeholders", "Duct Systems", "Ducts", "Electrical Equipment", "Electrical Fixtures", "Entourage", "Fire Alarm Devices", "Fire Protection", "Flex Ducts", "Flex Pipes", "Floors", "Food Service Equipment", "Furniture", "Furniture Systems", "Generic Models", "Grids", "Hardscape", "Levels", "Lighting Devices", "Lighting Fixtures","Mass", "Mechanical Control Devices", "Mechanical Equipment", "Mechanical Equipment Sets", "Medical Equipment", "MEP Fabrication Containment", "MEP Fabrication Ductwork", "MEP Fabrication Hangers", "MEP Fabrication Pipework", "Model Groups", "Nurse Call Devices", "Parking", 
 "Pipe Accessories", "Pipe Fittings", "Pipe Insulations", "Pipe Placeholders", "Pipes", "Piping Systems", "Planting", "Plumbing Equipment", "Plumbing Fixtures", "RVT Links", "Railings", "Ramps", "Rebar Shape", "Roads", "Roofs", "Security Devices", "Signage", "Site", "Specialty Equipment", "Sprinklers", "Stairs", "Structural Area Reinforcement", "Structural Beam Systems", "Structural Columns", "Structural Connections", "Structural Fabric Areas", "Structural Fabric Reinforcement", "Structural Foundations", "Structural Framing", "Structural Path Reinforcement", "Structural Rebar", "Structural Rebar Couplers", "Structural Stiffeners", "Structural Trusses", "Telephone Devices", "Temporary Structures", "Topography", "Vertical Circulation", "Walls", "Windows", "Wires"]
 
category_names_instance = ["Air Systems", "Air Terminals", "Analytical Links", "Analytical Members", "Analytical Nodes", "Analytical Openings", "Analytical Panels", "Analytical Pipe Connections", "Analytical Spaces", "Analytical Surfaces", "Areas", "Assemblies", "Audio Visual Devices",
 "Cable Tray Fittings", "Cable Tray Runs", "Cable Trays", "Casework", "Ceilings", "Columns", "Communication Devices", "Conduit Fittings", "Conduit Runs", "Conduits", "Curtain Panels", "Curtain Systems", "Curtain Wall Mullions", "Data Devices", "Detail Items", "Doors",
 "Duct Accessories", "Duct Fittings", "Duct Insulations", "Duct Linings", "Duct Placeholders", "Duct Systems", "Ducts", "Electrical Analytical Bus", "Electrical Analytical Loads", "Electrical Analytical Power Source", "Electrical Analytical Transfer Switch",
 "Electrical Analytical Transformer", "Electrical Circuits", "Electrical Equipment", "Electrical Fixtures", "Electrical Load Areas", "Entourage", "Fire Alarm Devices", "Fire Protection", "Flex Ducts", "Flex Pipes", "Floors", "Food Service Equipment", "Furniture", "Furniture Systems", "Generic Models", "Grids", "HVAC Zones", "Hardscape", "Levels", "Lighting Devices", "Lighting Fixtures", "MEP Fabrication Containment", "MEP Fabrication Ductwork", "MEP Fabrication Hangers", "MEP Fabrication Pipework", "Mass", "Materials", "Mechanical Control Devices", "Mechanical Equipment", "Mechanical Equipment Sets", "Medical Equipment", "Model Groups", "Nurse Call Devices", "Parking", "Parts", "Pipe Accessories", "Pipe Fittings", "Pipe Insulations", "Pipe Placeholders", "Pipes", "Piping Systems", "Planting", "Plumbing Equipment", "Plumbing Fixtures", "Project Information", "RVT Links", "Railings", "Ramps", "Rebar Shape", "Roads", "Roofs", "Rooms", "Schedules", "Security Devices", "Shaft Openings", "Sheets", "Signage", "Site", "Spaces", "Specialty Equipment", "Sprinklers", "Stairs", "Structural Area Reinforcement", "Structural Beam Systems", "Structural Columns", "Structural Connections", "Structural Fabric Areas", "Structural Fabric Reinforcement", "Structural Foundations", "Structural Framing", "Structural Path Reinforcement", "Structural Rebar", "Structural Rebar Couplers", "Structural Stiffeners", "Structural Trusses", "Switch System", "System-Zones", "Telephone Devices", "Temporary Structures", "Topography", "Vertical Circulation", "Views", "Walls", "Water Loops", "Windows", "Wires", "Zone Equipment"]

built_in_parameter_group = ["Analysis Results", "Analytical Alignment", "Analytical Model", "Constraints", "Construction",
"Data", "Dimensions", "Division Geometry", "Electrical", "Electrical - Circuiting", "Electrical - Lighting", "Electrical - Loads",
"Electrical Analysis", "Fire Protection", "Forces", "General", "Graphics", "Green Building Properties", "Identity Data",
"IFC Parameters", "Layers", "Life Safety", "Materials and Finishes", "Mechanical", "Mechanical Flow", "Mechanical Loads",
"Model Properties", "Moments", "Other", "Overall Legend", "Phasing", "Photometrics", "Plumbing", "Primary End", "Rebar Set", "Releases / Member Forces",
"Secondary End", "Segments and Fittings", "Set", "Slab Shape Edit", "Structural", "Structural Analysis", "Text", "Title Text", "Visibility"]